name: Android CI/CD with Fastlane (Firebase Only)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Ruby and Fastlane
        run: |
          choco install ruby -y --force
          echo "C:\tools\ruby33\bin" >> $GITHUB_PATH
          gem install bundler -NV
          gem install fastlane -NV
          fastlane -v  # Check if Fastlane is installed

      - name: Debug - List Files
        run: ls -R

      - name: Build and Upload to Firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_API_TOKEN: ${{ secrets.FIREBASE_API_TOKEN }}
        run: |
          echo "$GOOGLE_PLAY_JSON_KEY" > fastlane/service_account.json
          fastlane firebase
