name: Android CI/CD with Fastlane (Firebase Only)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set UTF-8 Locale
        run: |
          chcp 65001
          [System.Text.Encoding]::UTF8 | Out-Null

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: |
          ridk install 3  # Installs MSYS2 and dev tools required for native extensions

      - name: Install Ruby and Fastlane
        run: |
          choco install ruby --version=3.3.7 -y --force
          echo "C:\Ruby31-x64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          gem install bundler -NV
          gem install fastlane -NV
          fastlane -v  # Verify Fastlane installation

      - name: Debug - List Files
        run: ls -R

      - name: Decode google-services.json (Windows Fix)
        shell: pwsh
        run: |
            [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.GOOGLE_SERVICES_JSON }}")) | Out-File -FilePath "app/google-services.json" -Encoding utf8

      - name: Verify google-services.json
        run: ls -l app/google-services.json

      - name: Decode Firebase Service Account JSON
        shell: pwsh
        run: |
            [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}")) | Out-File -FilePath "fastlane/service_account.json" -Encoding utf8

      - name: Build and Upload to Firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_API_TOKEN: ${{ secrets.FIREBASE_API_TOKEN }}.0..
        run: |
          echo "$GOOGLE_PLAY_JSON_KEY" > fastlane/service_account.json
          fastlane testGoogle  # Run Fastlane without full path
