name: Android CI/CD with Fastlane (Firebase Only)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Ruby 3.3.7 and dependencies
        run: |
          choco install ruby --version=3.3.7 -y --force
          echo "C:\tools\ruby33\bin" >> $GITHUB_PATH
          ruby -v
          gem install bundler -NV
          ridk install 3  # Installs MSYS2 for missing dependencies

      - name: Build and Upload to Firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_API_TOKEN: ${{ secrets.FIREBASE_API_TOKEN }}
        run: |
          cd android
          fastlane firebase
